# Codecov configuration to make it a bit less noisy
coverage:
  status:
    patch:
      default:
        threshold: 1%
        target: auto
    project:
      default:
        threshold: 1%
        target: auto
comment:
  layout: "header"
  require_changes: false
  branches: null
  behavior: default
  flags: null
  paths: null
ignore:
  - "imdclient/data"
  - "imdclient/tests"
