name: GH Actions CI
on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
    schedule:
      # Weekly tests at midnight on Sundays run on main by default:
      #   Scheduled workflows run on the latest commit on the default or base branch.
      #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
      - cron: "0 0 * * 0"

defaults:
  run:
    shell: bash -l {0} 

jobs:
  environment-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

  main-tests:
    needs: environment-config
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build information
      run: |
        uname -a
        df -h
        ulimit -a

    # More info on options: https://github.com/conda-incubator/setup-miniconda
    - name: Install conda dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.12"
        environment-file: devtools/conda-envs/test_env.yaml
        add-pip-as-python-dependency: true

        channels: conda-forge, defaults

        activate-environment: imdreader-integration-test
        auto-update-conda: true
        auto-activate-base: false
        show-channel-urls: true
        miniconda-version: latest


    - name: Install MDAnalysis version
      uses: MDAnalysis/install-mdanalysis@main
      with:
        version: "2.7.0"
        install-tests: true
        installer: conda
        shell: bash -l {0} 
      
    - name: Python information
      run: |
        which python
        which pip
        pip list
        conda info
        conda list

    - name: Clone lammps fork
      uses: actions/checkout@v4
      with:
        repository: ljwoods2/lammps
        ref: imd-v3
        path: lammps

    - name: Build lammps
      run: |
        cd lammps
        mkdir build
        cd build
        cmake ../cmake/ -D PKG_MISC=yes
        cmake --build .
        make install
        lmp -h

    - name: Run lammps tests
      run: |
        pytest -n auto -v --color=yes imdclient/tests/test_lammps.py
