name: GH Actions CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

defaults:
  run:
    shell: bash -l {0} 



jobs:
  namd-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build information
        run: |
          uname -a
          df -h
          ulimit -a

      # More info on options: https://github.com/conda-incubator/setup-miniconda
      - name: Install conda dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.12"
          environment-file: devtools/conda-envs/test_env.yaml
          add-pip-as-python-dependency: true

          channels: conda-forge, defaults

          activate-environment: imdreader-integration-test
          auto-update-conda: true
          auto-activate-base: false
          show-channel-urls: true
          miniconda-version: latest


      - name: Install MDAnalysis version
        uses: MDAnalysis/install-mdanalysis@main
        with:
          version: "2.7.0"
          install-tests: true
          installer: conda
          shell: bash -l {0} 
        
      - name: Python information
        run: |
          which python
          which pip
          pip list
          conda info
          conda list

      - name: Clone namd fork
        uses: actions/checkout@v4
        with:
          repository: amruthesht/namd-3.0
          ref: heekun_testruns
          path: namd

      - name: Build namd
        run: |
          cd namd/namd-3.0
          tar xf charm-8.0.0.tar
          cd charm-8.0.0
          ./build charm++ ucx-linux-x86_64 ompipmix --with-production
          cd ucx-linux-x86_64-ompipmix/tests/charm++/megatest
          make
          cd ../../../../..
          wget http://www.ks.uiuc.edu/Research/namd/libraries/fftw-linux-x86_64.tar.gz
          tar xzf fftw-linux-x86_64.tar.gz
          mv linux-x86_64 fftw
          wget http://www.ks.uiuc.edu/Research/namd/libraries/tcl8.6.13-linux-x86_64.tar.gz
          wget http://www.ks.uiuc.edu/Research/namd/libraries/tcl8.6.13-linux-x86_64-threaded.tar.gz
          tar xzf tcl8.6.13-linux-x86_64.tar.gz
          tar xzf tcl8.6.13-linux-x86_64-threaded.tar.gz
          mv tcl8.6.13-linux-x86_64 tcl
          mv tcl8.6.13-linux-x86_64-threaded tcl-threaded
          ./config Linux-x86_64-g++ --charm-arch ucx-linux-x86_64-ompipmix
          cd Linux-x86_64-g++
          make

      - name: Run namd tests
        run: |
          pytest -n auto -v --color=yes imdclient/tests/test_namd.py
